### ISSUE TITLE
App Purpose

### ISSUE THREAD

**Issue by RogueMaster** [nymda/FlipperZeroBrainfuck#1]
Hi nymda,

Could you add a ReadMe with app purpose? Thanks for all your flipper development 😄 

Looking forward to your future apps

**Comment by RogueMaster** [comment]
The comments you have added are funny lol

**Comment by nymda** [comment]
hey, its you! i added a readme, only really stuck this on github so the only copy isnt just on my PC. its very unfinished at the moment but im hoping to have the intepreter working to some extent today.
