### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Milk-Cool** [nymda/FlipperZeroBrainfuck#2]
Error:
```
In file included from applications_user/FlipperZeroBrainfuck/brainfuck.c:1:
applications_user/FlipperZeroBrainfuck/brainfuck_i.h:32:10: fatal error: brainfuck_icons.h: No such file or directory
   32 | #include <brainfuck_icons.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by RogueMaster** [comment]
If you renamed appid you may need to change this...

**Comment by RogueMaster** [comment]
such as Brainfuck_icons.h

**Comment by Milk-Cool** [comment]
i did not change anything

**Comment by Milk-Cool** [comment]
oh i get it. it's named "Brainfuck" instead of "brainfuck" for some reason

**Comment by Milk-Cool** [comment]
now I get this error:
```
applications_user/FlipperZeroBrainfuck/views/bf_dev_env.c:125:29: error: 'FontBatteryPercent' undeclared (first use in this function)
  125 |     canvas_set_font(canvas, FontBatteryPercent);
  ```
  
  does this only compile on some kind of custom firmware?

**Comment by RogueMaster** [comment]
Yeah, you need to add lines and files possibly for that font...

**Comment by RogueMaster** [comment]
Initial battery % change had the font...

**Comment by RogueMaster** [comment]
https://github.com/flipperdevices/flipperzero-firmware/compare/dev...McAzzaMan:flipperzero-firmware:BatteryPercentageView see here for needed changes

**Comment by Milk-Cool** [comment]
ok it worked
