### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by grugnoymeme** [nymda/FlipperZeroBrainfuck#4]
Hi if i leave the flipper with the app opened without touching for about a minute, is gonna lock everything and it needs to be rebooted... i use it o rm, with nu api and everything updated.

**Comment by nymda** [comment]
thanks for the report, i'll check this out. which screen are you leaving it on?

**Comment by nymda** [comment]
not been able to reproduce this

**Comment by grugnoymeme** [comment]
sorry i didn't get it
